targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "warn"
allow-osi-fsf-free = "neither"
confidence-threshold = 0.93
default = "deny"
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "Zlib" ]

[bans]
multiple-versions = "deny"
highlight = "all"
skip = [
    # Blocked on http updating bytes to 1.0.x
    { name = "bytes", version = "0.5.6" },
    
    # Blocked on tempfile updating cfg=if to 1.0.x
    { name = "cfg-if", version = "0.1.10" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
